### PR TITLE
LPS-51051 init last login date anyway

### PR DESCRIPTION
**Pull request by topolik**

### CODE REVIEW

**Comment by bejondshao** [comment]
Hi olafk,

Do you have any time to review this?

**Comment by bejondshao** [comment]
Hi @olafk ,

I'm afraid merge pull request to your repository is not enough. We usually send new pull request to other people, like brian, if you pass the pull request.

Bejond

**Comment by topolik** [comment]
Hi @bejondshao,

I'm OK with the fix and Olaf wrote me that it's alright. I believe you can send it directly to Hugo/Brian.

Thank you.

**Comment by olafk** [comment]
Yup, sorry. I have lost sight of it and have been travelling quite a bit.

Now I was in training, did it on the side and first wanted to straighten
my master's history - then got involved in the training again so that I
put this on the backburner.

It might currently be easier to follow Tom's suggestion and forward - as
I'm typically not fixing in Liferay, I'll also have a hard time
identifying whom to forward to.

Otherwise please allow a few more days. It's now back on my list.

Sorry for the delay.
Olaf

Am 13.03.2015 um 03:16 schrieb Bejond Shao:

**Pull request merged**
